import '@/styles/globals.css'
import { dir } from 'i18next'
import { i18n } from '@/../i18n'
import { Header } from '@/components/header'
import { firaCode } from '@/fonts'
import { Metadata } from 'next'
import { ReactNode } from 'react'

export async function generateStaticParams() {
  return i18n.locales.map((lang: string) => ({ lang }))
}

export const metadata: Metadata = {
  title: 'Portifólio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { lang }
}: {
  children: ReactNode,
  params: { lang: string }
}) {
  return (
    <html lang={lang} dir={dir(lang)}>
        <body
          className={`
        ${firaCode.className}
       bg-red text-gray-950
       dark:bg-gray-950 dark:text-white
       `}>

          <Header lang={lang} />
          {children}
        </body>
    </html>
  )
}
